ITEM.name = "Chocolate"
ITEM.uniqueID = "food_chocolate"
ITEM.model = "models/props_lab/box01a.mdl"
ITEM.hungerAmount = 20
ITEM.foodDesc = "A box of delicious chocolates."
ITEM.quantity = 1
ITEM.price = 4
ITEM.width = 2
ITEM.height = 2
ITEM.container = "j_empty_chocolate_box"
ITEM.dropscontainer = true
ITEM.cookable = false
