ITEM.name = "Dog Food"
ITEM.uniqueID = "food_dog_food"
ITEM.model = "models/props_junk/petfoodbag01.mdl"
ITEM.hungerAmount = 30
ITEM.foodDesc = "A bag of old dog food."
ITEM.quantity = 10
ITEM.price = 7
ITEM.width = 3
ITEM.height = 4
ITEM.container = "j_empty_dog_food"
ITEM.dropscontainer = true
ITEM.cookable = false
