ITEM.name = "Milk Jug"
ITEM.uniqueID = "food_milk_jug"
ITEM.model = "models/props_junk/garbage_milkcarton001a.mdl"
ITEM.hungerAmount = 12
ITEM.foodDesc = "A jug filled with milk."
ITEM.quantity = 6
ITEM.price = 6
ITEM.width = 2
ITEM.height = 2
ITEM.container = "j_empty_milk_jug"
ITEM.dropscontainer = true
ITEM.cookable = false
