ITEM.name = "Strange Chip"
ITEM.uniqueID = "cube_chip"
ITEM.desc = "A thin metal chip, it is labelled 'E.N.D. Chip'."
ITEM.model = "models/gibs/metal_gib4.mdl"
ITEM.flag = "j"
ITEM.category = "Experimental Nourishment Device"